version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /download
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-npm:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /download
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-docker:
        patterns:
          - "*"
