- id: pull
  execute-command: /var/www/tiles.versatiles.org/config/webhook/pull.sh
  command-working-directory: /var/www/tiles.versatiles.org/
  trigger-rule:
    and:
    - match:
        type: payload-hmac-sha1
        secret: "%SECRET%"
        parameter:
          source: header
          name: X-Hub-Signature
    - match:
        type: value
        value: refs/heads/main
        parameter:
          source: payload
          name: ref
