/**
 * Site generation utilities for download.versatiles.org.
 *
 * Writes file group data as JSON, runs SvelteKit's `vite build` to
 * pre-render the site, then copies the generated HTML and RSS files
 * to the content folder. Produces:
 *
 * - `index.html` — the main overview page listing all file groups
 * - `feed-<slug>.xml` — per-group RSS feeds for version updates
 *
 * These outputs are wrapped in `FileRef` objects so they can be
 * included in the final NGINX configuration and file inventory.
 */
import { writeFileSync, renameSync, mkdirSync, readdirSync, copyFileSync, statSync } from 'fs';
import { execSync } from 'child_process';
import type { FileGroup } from '../file/file_group.js';
import { FileRef } from '../file/file_ref.js';
import { resolve } from 'path';

/**
 * Generates the static site using SvelteKit and copies output to the
 * content folder.
 *
 * Steps:
 * 1. Writes `data/fileGroups.json` with serialised file group data
 * 2. Runs `npx vite build` to pre-render all pages
 * 3. Copies `build/index.html` and `build/feed-*.xml` to `contentFolder`
 * 4. Returns `FileRef` objects for inclusion in NGINX config
 */
export function generateSite(fileGroups: FileGroup[], contentFolder: string): { htmlRef: FileRef; rssRefs: FileRef[] } {
	console.log('Generating site...');

	// 1. Write data file for SvelteKit to consume
	const dataDir = resolve('data');
	mkdirSync(dataDir, { recursive: true });
	const dataPath = resolve(dataDir, 'fileGroups.json');
	writeFileSync(dataPath, JSON.stringify(fileGroups));

	// 2. Run vite build (SvelteKit static adapter)
	console.log(' - Running vite build...');
	execSync('npx vite build', { stdio: 'inherit' });

	// 3. Copy build output to content folder
	const buildDir = resolve('build');

	// Copy index.html
	const indexSrc = resolve(buildDir, 'index.html');
	const indexDest = resolve(contentFolder, 'index.html');
	const indexTmp = indexDest + '.tmp';
	copyFileSync(indexSrc, indexTmp);
	renameSync(indexTmp, indexDest);
	const htmlRef = new FileRef(indexDest, '/index.html');

	// Copy feed-*.xml files
	const rssRefs: FileRef[] = [];
	const buildFiles = readdirSync(buildDir);
	for (const file of buildFiles) {
		if (file.startsWith('feed-') && file.endsWith('.xml')) {
			const src = resolve(buildDir, file);
			const dest = resolve(contentFolder, file);
			const tmp = dest + '.tmp';
			copyFileSync(src, tmp);
			renameSync(tmp, dest);
			rssRefs.push(new FileRef(dest, '/' + file));
		}
	}

	// Copy _app/ directory (CSS and other static assets generated by SvelteKit)
	const appSrcDir = resolve(buildDir, '_app');
	const appDestDir = resolve(contentFolder, '_app');
	copyDirSync(appSrcDir, appDestDir);

	console.log(' - Site generation complete');
	return { htmlRef, rssRefs };
}

/** Recursively copies a directory. */
function copyDirSync(src: string, dest: string) {
	mkdirSync(dest, { recursive: true });
	for (const entry of readdirSync(src)) {
		const srcPath = resolve(src, entry);
		const destPath = resolve(dest, entry);
		if (statSync(srcPath).isDirectory()) {
			copyDirSync(srcPath, destPath);
		} else {
			copyFileSync(srcPath, destPath);
		}
	}
}
