name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./bin
          additional_files: update-tiles.sh

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate docker compose
        run: |
          cp template.env .env
          docker compose config --quiet

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: YAML lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: compose.yaml
          config_data: |
            extends: relaxed
            rules:
              line-length: disable
